import {
  ExamCategory,
  ExamPatternConfig,
  Question,
  MockTest,
  PreviousYearPaper,
  HierarchicalSubjectNode,
  TestAttempt
} from './types';

export const EXAM_PATTERNS: Record<ExamCategory, ExamPatternConfig> = {
  CGSSB: {
    id: 'CGSSB',
    name: 'CGSSB (Chhattisgarh Professional Examination Board / Vyapam)',
    shortName: 'CGSSB / Vyapam',
    totalQuestions: 100,
    durationMinutes: 120,
    marksPerCorrect: 1.0,
    negativeMarksRatio: 1 / 3,
    negativeMarksPerWrong: 0.333,
    description: 'Exam pattern: 100 questions, 1 mark for right answer, minus 1/3rd for wrong answer and 2 hours exam time.',
    color: '#10B981',
    badge: '100 Qs • +1 • -⅓ • 120 Mins',
    isComingSoon: false,
  },
  CGPSC: {
    id: 'CGPSC',
    name: 'CGPSC (Chhattisgarh Public Service Commission - SSE)',
    shortName: 'CGPSC SSE',
    totalQuestions: 100,
    durationMinutes: 120,
    marksPerCorrect: 2.0,
    negativeMarksRatio: 1 / 3,
    negativeMarksPerWrong: 0.667, // 1/3 of 2 marks = 0.667 or 1/3 per syllabus
    description: 'Exam pattern: 100 questions based on CGPSC SSE syllabus. 2 marks for correct answer and minus 1/3 marks for wrong answers.',
    color: '#3B82F6',
    badge: '100 Qs • +2 • -⅓ • 120 Mins',
    isComingSoon: false,
  },
  SWAMI_ATMANAND: {
    id: 'SWAMI_ATMANAND',
    name: 'Swami Atmanand English Medium School Recruitment',
    shortName: 'Swami Atmanand',
    totalQuestions: 100,
    durationMinutes: 120,
    marksPerCorrect: 1.0,
    negativeMarksRatio: 1 / 3,
    negativeMarksPerWrong: 0.333,
    description: 'Exam pattern: 100 questions, 1 mark for right answer, minus 1/3rd for wrong answer and 2 hours exam time.',
    color: '#8B5CF6',
    badge: '100 Qs • +1 • -⅓ • 120 Mins',
    isComingSoon: false,
  },
  CENTRAL_EXAMS: {
    id: 'CENTRAL_EXAMS',
    name: 'Central Exams (Railway RRB, SSC CGL/CHSL, Banking IBPS/SBI, UPSC)',
    shortName: 'Central (SSC, Rail, Bank, UPSC)',
    totalQuestions: 100,
    durationMinutes: 60,
    marksPerCorrect: 1.0,
    negativeMarksRatio: 0.25,
    negativeMarksPerWrong: 0.25,
    description: 'Central government recruitment exams including Staff Selection Commission, Railway Recruitment Boards, Banking & UPSC Prelims.',
    color: '#F59E0B',
    badge: 'Coming Soon',
    isComingSoon: true,
  },
};

export const HIERARCHY_TREE: HierarchicalSubjectNode[] = [
  {
    subject: 'Chhattisgarh Special Knowledge',
    topics: [
      {
        name: 'History of Chhattisgarh',
        subtopics: ['Kalchuri Dynasty', 'Maratha Rule & British Period', 'Tribal Revolts & Freedom Struggle', 'Modern State Formation (2000)'],
      },
      {
        name: 'Geography & Natural Resources',
        subtopics: ['River Basins (Mahanadi, Indravati)', 'Forests & National Parks', 'Minerals & Industrial Zones', 'Climate & Soil Types'],
      },
      {
        name: 'Culture, Tribes & Tourism',
        subtopics: ['Bastar Dussehra & Madai Mela', 'Tribal Traditions (Gond, Baiga, Maria)', 'Folk Dances (Karma, Raut Nacha, Panthi)', 'Historical Temples & Archeology'],
      },
      {
        name: 'Administration & Economy',
        subtopics: ['Panchayati Raj & Urban Local Bodies', 'State Budget & Welfare Schemes', 'Agriculture & Minor Forest Produce', 'State Legislature & Districts'],
      },
    ],
  },
  {
    subject: 'General Mental Ability & Reasoning',
    topics: [
      {
        name: 'Analytical Reasoning',
        subtopics: ['Coding-Decoding', 'Blood Relations', 'Syllogism & Logical Deduction', 'Direction Sense Test'],
      },
      {
        name: 'Quantitative Aptitude',
        subtopics: ['Percentages & Profit-Loss', 'Ratio & Proportion', 'Time, Speed & Distance', 'Data Interpretation'],
      },
    ],
  },
  {
    subject: 'General Hindi & Chhattisgarhi Language',
    topics: [
      {
        name: 'Chhattisgarhi Bhasha & Vyakaran',
        subtopics: ['Idioms & Proverbs (Hana)', 'Chhattisgarhi Nouns & Pronouns', 'Local Dialects & Terminology'],
      },
      {
        name: 'Samanya Hindi',
        subtopics: ['Sandhi & Samas', 'Paryayvachi & Vilom Shabd', 'Muhavare & Lokoktiyan', 'Vartani Shuddhi'],
      },
    ],
  },
  {
    subject: 'General Science & Computer Knowledge',
    topics: [
      {
        name: 'Computer Fundamentals (Vyapam)',
        subtopics: ['MS Office & Operating Systems', 'Internet & Cybersecurity', 'Computer Hardware & Memory', 'Abbreviations & File Formats'],
      },
      {
        name: 'Basic Science',
        subtopics: ['Physics Concepts & Units', 'Human Physiology & Nutrition', 'Ecology & Environmental Science'],
      },
    ],
  },
  {
    subject: 'Child Pedagogy & Teaching Methodology',
    topics: [
      {
        name: 'Educational Psychology',
        subtopics: ['Child Development Stages', 'Learning Theories (Piaget, Vygotsky)', 'Inclusive Education & CWSN'],
      },
      {
        name: 'Pedagogy & Curriculum',
        subtopics: ['Teaching Learning Materials (TLM)', 'Continuous & Comprehensive Evaluation (CCE)', 'National Education Policy 2020'],
      },
    ],
  },
];

export const INITIAL_QUESTIONS: Question[] = [
  // 1
  {
    id: 'q-cg-01',
    subject: 'Chhattisgarh Special Knowledge',
    topic: 'History of Chhattisgarh',
    subtopic: 'Kalchuri Dynasty',
    difficulty: 'Medium',
    category: 'CGSSB',
    questionText: 'Who was the founder of the Ratanpur branch of the Kalchuri dynasty in Chhattisgarh?',
    questionHindi: 'छत्तीसगढ़ में कलचुरी वंश की रतनपुर शाखा के संस्थापक कौन थे?',
    options: [
      { id: 'A', text: 'Kalingaraj', textHindi: 'कलिंगराज' },
      { id: 'B', text: 'Ratnadeva I', textHindi: 'रत्नदेव प्रथम' },
      { id: 'C', text: 'Kamalraja', textHindi: 'कमलराज' },
      { id: 'D', text: 'Prithvideva I', textHindi: 'पृथ्वीदेव प्रथम' },
    ],
    correctOption: 'A',
    marks: 1.0,
    negativeMarks: 0.333,
    explanation: 'Around 1000 AD, Kalingaraj founded the Ratanpur branch of the Kalchuris by establishing his capital at Tumman before Ratnadeva I shifted it to Ratanpur.',
    explanationHindi: 'लगभग 1000 ईस्वी में कलिंगराज ने तुम्माण को राजधानी बनाकर कलचुरी वंश की स्थापना की, जिसे बाद में रत्नदेव प्रथम ने रतनपुर स्थानांतरित किया।',
    pypSource: 'CGSSB Combined 2022',
    pypAppearances: [
      { examName: 'CGSSB Combined Exam', year: 2022, shift: 'Shift 1' },
      { examName: 'CGPSC SSE Prelims Paper-I', year: 2018, shift: 'General Studies' },
      { examName: 'CG Vyapam Revenue Inspector (RI)', year: 2015 },
    ],
    createdAt: '2024-01-10',
  },
  // 2
  {
    id: 'q-cg-02',
    subject: 'Chhattisgarh Special Knowledge',
    topic: 'Geography & Natural Resources',
    subtopic: 'River Basins (Mahanadi, Indravati)',
    difficulty: 'Easy',
    category: 'CGSSB',
    questionText: 'Which waterfall in Chhattisgarh is famously known as the "Niagara Falls of India"?',
    questionHindi: 'छत्तीसगढ़ का कौन सा जलप्रपात "भारत का नियाग्रा जलप्रपात" के नाम से जाना जाता है?',
    options: [
      { id: 'A', text: 'Teerathgarh Waterfall', textHindi: 'तीरथगढ़ जलप्रपात' },
      { id: 'B', text: 'Chitrakote Waterfall', textHindi: 'चित्रकोट जलप्रपात' },
      { id: 'C', text: 'Amritdhara Waterfall', textHindi: 'अमृतधारा जलप्रपात' },
      { id: 'D', text: 'Ghatarani Waterfall', textHindi: 'घटारानी जलप्रपात' },
    ],
    correctOption: 'B',
    marks: 1.0,
    negativeMarks: 0.333,
    explanation: 'Chitrakote Waterfall is situated on the Indravati River in Bastar district. Due to its horseshoe shape and immense volume of water during the monsoon, it is widely called the Niagara of India.',
    explanationHindi: 'चित्रकोट जलप्रपात बस्तर जिले में इंद्रावती नदी पर स्थित है। घोड़े की नाल जैसे आकार और विशाल जलराशि के कारण इसे भारत का नियाग्रा कहा जाता है।',
    pypSource: 'CGPSC SSE 2021',
    pypAppearances: [
      { examName: 'CGPSC SSE Prelims Paper-I', year: 2021, shift: 'General Studies' },
      { examName: 'CGSSB Patwari Selection Exam', year: 2019 },
      { examName: 'CG Vyapam Forest Guard', year: 2022 },
      { examName: 'CG Police Sub-Inspector (SI)', year: 2023 },
    ],
    createdAt: '2024-01-11',
  },
  // 3
  {
    id: 'q-cg-03',
    subject: 'Chhattisgarh Special Knowledge',
    topic: 'Culture, Tribes & Tourism',
    subtopic: 'Bastar Dussehra & Madai Mela',
    difficulty: 'Medium',
    category: 'CGSSB',
    questionText: 'How many days does the historic world-famous Bastar Dussehra festival last?',
    questionHindi: 'ऐतिहासिक विश्व प्रसिद्ध बस्तर दशहरा उत्सव कितने दिनों तक मनाया जाता है?',
    options: [
      { id: 'A', text: '10 Days', textHindi: '10 दिन' },
      { id: 'B', text: '45 Days', textHindi: '45 दिन' },
      { id: 'C', text: '75 Days', textHindi: '75 दिन' },
      { id: 'D', text: '90 Days', textHindi: '90 दिन' },
    ],
    correctOption: 'C',
    marks: 1.0,
    negativeMarks: 0.333,
    explanation: 'Bastar Dussehra is unique because it is celebrated for 75 days, dedicated to Goddess Danteshwari, and does not commemorate the victory of Rama over Ravana.',
    explanationHindi: 'बस्तर दशहरा 75 दिनों तक चलने वाला विश्व का सबसे लंबा त्यौहार है जो मां दंतेश्वरी को समर्पित है।',
    pypSource: 'CGSSB Patwari 2023',
    pypAppearances: [
      { examName: 'CGSSB Patwari Exam', year: 2023 },
      { examName: 'CGPSC State Service Prelims', year: 2017 },
      { examName: 'CG Rural Development Officer', year: 2020 },
    ],
    createdAt: '2024-01-12',
  },
  // 4
  {
    id: 'q-cg-04',
    subject: 'General Science & Computer Knowledge',
    topic: 'Computer Fundamentals (Vyapam)',
    subtopic: 'Internet & Cybersecurity',
    difficulty: 'Easy',
    category: 'CGSSB',
    questionText: 'Which protocol is used for secure end-to-end communication over the World Wide Web?',
    questionHindi: 'वर्ल्ड वाइड वेब पर सुरक्षित एंड-टू-एंड संचार के लिए किस प्रोटोकॉल का उपयोग किया जाता है?',
    options: [
      { id: 'A', text: 'FTP', textHindi: 'FTP' },
      { id: 'B', text: 'HTTP', textHindi: 'HTTP' },
      { id: 'C', text: 'HTTPS', textHindi: 'HTTPS' },
      { id: 'D', text: 'SMTP', textHindi: 'SMTP' },
    ],
    correctOption: 'C',
    marks: 1.0,
    negativeMarks: 0.333,
    explanation: 'HTTPS (Hypertext Transfer Protocol Secure) encrypts data using SSL/TLS, ensuring secure transmission of sensitive data.',
    explanationHindi: 'HTTPS (हाइपरटेक्स्ट ट्रांसफर प्रोटोकॉल सिक्योर) डेटा को SSL/TLS के माध्यम से एन्क्रिप्ट करता है।',
    pypSource: 'CGSSB Hostel Warden 2022',
    pypAppearances: [
      { examName: 'CGSSB Hostel Warden Exam', year: 2022 },
      { examName: 'CG Vyapam Sub-Engineer Exam', year: 2020 },
    ],
    createdAt: '2024-01-14',
  },
  // 5
  {
    id: 'q-cg-05',
    subject: 'General Hindi & Chhattisgarhi Language',
    topic: 'Chhattisgarhi Bhasha & Vyakaran',
    subtopic: 'Idioms & Proverbs (Hana)',
    difficulty: 'Hard',
    category: 'CGSSB',
    questionText: 'What is the meaning of the Chhattisgarhi Hana (proverb): "पेट म दाढ़ी होना" (Pet ma Dadhi hona)?',
    questionHindi: 'छत्तीसगढ़ी मुहावरे/हाना "पेट म दाढ़ी होना" का सटीक अर्थ क्या है?',
    options: [
      { id: 'A', text: 'To be very hungry', textHindi: 'अत्यधिक भूखा होना' },
      { id: 'B', text: 'To be shrewd and clever beyond one\'s young age', textHindi: 'कम उम्र में बहुत चतुर व धूर्त होना' },
      { id: 'C', text: 'To suffer from stomach illness', textHindi: 'पेट का गंभीर रोगी होना' },
      { id: 'D', text: 'To become very old quickly', textHindi: 'असमय बूढ़ा हो जाना' },
    ],
    correctOption: 'B',
    marks: 1.0,
    negativeMarks: 0.333,
    explanation: 'In Chhattisgarhi folk literature, "पेट म दाढ़ी होना" signifies being deceptive, worldly-wise, or unnaturally shrewd from childhood.',
    explanationHindi: 'छत्तीसगढ़ी में "पेट म दाढ़ी होना" का तात्पर्य बचपन या कम उम्र से ही बहुत चतुर, धूर्त या कूटनीतिज्ञ होना है।',
    pypSource: 'CGSSB RI 2021',
    pypAppearances: [
      { examName: 'CGSSB Revenue Inspector (RI)', year: 2021 },
      { examName: 'CGPSC State Service Mains Hindi Paper', year: 2019 },
      { examName: 'CG Vyapam Assistant Grade-III', year: 2017 },
    ],
    createdAt: '2024-01-15',
  },
  // 6
  {
    id: 'q-cg-06',
    subject: 'General Mental Ability & Reasoning',
    topic: 'Analytical Reasoning',
    subtopic: 'Coding-Decoding',
    difficulty: 'Medium',
    category: 'CGSSB',
    questionText: 'If RAIPUR is coded as SBJQVCS, how will BILASPUR be coded in that same pattern?',
    questionHindi: 'यदि किसी कूटभाषा में RAIPUR को SBJQVS लिखा जाता है (प्रत्येक अक्षर +1), तो BILASPUR को क्या लिखा जाएगा?',
    options: [
      { id: 'A', text: 'CJM BT QVS', textHindi: 'CJMBTQVS' },
      { id: 'B', text: 'CJMBTQVR', textHindi: 'CJMBTQVR' },
      { id: 'C', text: 'CJNBTQVS', textHindi: 'CJNBTQVS' },
      { id: 'D', text: 'CKNBTQVS', textHindi: 'CKNBTQVS' },
    ],
    correctOption: 'A',
    marks: 1.0,
    negativeMarks: 0.333,
    explanation: 'Each letter is shifted by +1 in the alphabet: B->C, I->J, L->M, A->B, S->T, P->Q, U->V, R->S = CJMBTQVS.',
    explanationHindi: 'प्रत्येक अक्षर में +1 की वृद्धि हुई है: B(+1)=C, I(+1)=J, L(+1)=M, A(+1)=B, S(+1)=T, P(+1)=Q, U(+1)=V, R(+1)=S.',
    pypSource: 'CGSSB Combined 2023',
    pypAppearances: [
      { examName: 'CGSSB Combined Exam', year: 2023 },
      { examName: 'CG Police Constable', year: 2021 },
    ],
    createdAt: '2024-01-16',
  },
  // 7
  {
    id: 'q-cg-07',
    subject: 'Chhattisgarh Special Knowledge',
    topic: 'History of Chhattisgarh',
    subtopic: 'Tribal Revolts & Freedom Struggle',
    difficulty: 'Hard',
    category: 'CGSSB',
    questionText: 'Who was the leader of the famous Bhumkal Revolt of Bastar in 1910?',
    questionHindi: '1910 के ऐतिहासिक बस्तर भूमकाल विद्रोह के प्रमुख जननायक कौन थे?',
    options: [
      { id: 'A', text: 'Gundadhur', textHindi: 'गुंडाधुर' },
      { id: 'B', text: 'Gend Singh', textHindi: 'गेंद सिंह' },
      { id: 'C', text: 'Veer Narayan Singh', textHindi: 'वीर नारायण सिंह' },
      { id: 'D', text: 'Hanuman Singh', textHindi: 'हनुमान सिंह' },
    ],
    correctOption: 'A',
    marks: 1.0,
    negativeMarks: 0.333,
    explanation: 'Gundadhur of Nethanar village was the military commander and supreme leader of the 1910 Bhumkal revolt against British forest policies and oppression.',
    explanationHindi: 'नेतानार के वीर गुंडाधुर ने 1910 में अंग्रेजों के शोषण व वन कानूनों के खिलाफ प्रसिद्ध भूमकाल विद्रोह का नेतृत्व किया था।',
    pypSource: 'CGPSC SSE 2022',
    pypAppearances: [
      { examName: 'CGPSC SSE Prelims Paper-I', year: 2022 },
      { examName: 'CGSSB Assistant Teacher Recruitment', year: 2021 },
      { examName: 'CG Police Sub-Inspector (SI)', year: 2018 },
    ],
    createdAt: '2024-01-17',
  },
  // 8
  {
    id: 'q-cg-08',
    subject: 'Chhattisgarh Special Knowledge',
    topic: 'Administration & Economy',
    subtopic: 'Panchayati Raj & Urban Local Bodies',
    difficulty: 'Medium',
    category: 'CGSSB',
    questionText: 'In Chhattisgarh Panchayati Raj Act 1993, what is the minimum quorum required for a Gram Sabha meeting?',
    questionHindi: 'छत्तीसगढ़ पंचायती राज अधिनियम 1993 के तहत ग्राम सभा की बैठक के लिए न्यूनतम गणपूर्ति (कोरम) कितनी है?',
    options: [
      { id: 'A', text: '1/10th of total members, with at least 1/3rd being women', textHindi: 'कुल सदस्यों का 1/10, जिसमें कम से कम 1/3 महिला सदस्य हों' },
      { id: 'B', text: '1/5th of total members, with at least 1/2 being women', textHindi: 'कुल सदस्यों का 1/5, जिसमें कम से कम 1/2 महिला सदस्य हों' },
      { id: 'C', text: '1/4th of total members without gender quota', textHindi: 'कुल सदस्यों का 1/4' },
      { id: 'D', text: '1/3rd of total members', textHindi: 'कुल सदस्यों का 1/3' },
    ],
    correctOption: 'A',
    marks: 1.0,
    negativeMarks: 0.333,
    explanation: 'Under Section 6 of the CG Panchayati Raj Act 1993, the quorum for Gram Sabha is 1/10th of total voters, with at least one-third of present members being women.',
    explanationHindi: 'छत्तीसगढ़ पंचायती राज अधिनियम के तहत ग्राम सभा का कोरम 1/10 सदस्य है, जिसमें कम से कम 1/3 महिलाओं की उपस्थिति अनिवार्य है।',
    pypSource: 'CGPSC SSE 2020',
    pypAppearances: [
      { examName: 'CGPSC SSE Prelims', year: 2020 },
      { examName: 'CG Vyapam Chief Executive Officer (Panchayat)', year: 2017 },
      { examName: 'CGSSB Patwari Exam', year: 2016 },
    ],
    createdAt: '2024-01-18',
  },
  // 9
  {
    id: 'q-cg-09',
    subject: 'General Science & Computer Knowledge',
    topic: 'Computer Fundamentals (Vyapam)',
    subtopic: 'Computer Hardware & Memory',
    difficulty: 'Easy',
    category: 'CGSSB',
    questionText: 'Which memory type is non-volatile and retains its contents even when computer power is switched off?',
    questionHindi: 'निम्नलिखित में से कौन सी मेमोरी नॉन-वोलेटाइल (स्थायी) है जो कंप्यूटर बंद होने पर भी डेटा सुरक्षित रखती है?',
    options: [
      { id: 'A', text: 'RAM (Random Access Memory)', textHindi: 'RAM' },
      { id: 'B', text: 'ROM (Read Only Memory)', textHindi: 'ROM' },
      { id: 'C', text: 'Cache Memory', textHindi: 'कैश मेमोरी' },
      { id: 'D', text: 'Registers', textHindi: 'रजिस्टर्स' },
    ],
    correctOption: 'B',
    marks: 1.0,
    negativeMarks: 0.333,
    explanation: 'ROM is non-volatile memory storing firmware and bootstrap code that persists without power, unlike volatile RAM.',
    explanationHindi: 'ROM (रीड ओनली मेमोरी) एक नॉन-वोलेटाइल मेमोरी है जिसका डेटा बिजली कट जाने पर भी नष्ट नहीं होता।',
    pypSource: 'CGSSB Combined 2023',
    pypAppearances: [
      { examName: 'CGSSB Combined Exam', year: 2023 },
      { examName: 'CG Vyapam Data Entry Operator (DEO)', year: 2021 },
      { examName: 'CGSSB Hostel Warden', year: 2019 },
    ],
    createdAt: '2024-01-19',
  },
  // 10
  {
    id: 'q-cg-10',
    subject: 'Chhattisgarh Special Knowledge',
    topic: 'Culture, Tribes & Tourism',
    subtopic: 'Folk Dances (Karma, Raut Nacha, Panthi)',
    difficulty: 'Easy',
    category: 'CGSSB',
    questionText: 'Panthi dance of Chhattisgarh is primarily associated with which spiritual community/saint?',
    questionHindi: 'छत्तीसगढ़ का विख्यात पंथी नृत्य मुख्यतः किस पंथ/संत की शिक्षाओं से जुड़ा हुआ है?',
    options: [
      { id: 'A', text: 'Satnami Community & Guru Ghasidas', textHindi: 'सतनामी समुदाय एवं गुरु घासीदास जी' },
      { id: 'B', text: 'Kabir Panth', textHindi: 'कबीर पंथ' },
      { id: 'C', text: 'Vaishnav Tradition', textHindi: 'वैष्णव परंपरा' },
      { id: 'D', text: 'Nath Sect', textHindi: 'नाथ संप्रदाय' },
    ],
    correctOption: 'A',
    marks: 1.0,
    negativeMarks: 0.333,
    explanation: 'Panthi dance is an energetic, devotional acrobatic dance performed by the Satnami community, celebrating the truth and teachings of Guru Ghasidas.',
    explanationHindi: 'पंथी नृत्य सतनामी समाज द्वारा गुरु घासीदास जी की जयंती और उनके उपदेशों के सम्मान में अत्यंत उत्साह और पिरामिड बनाकर किया जाता है।',
    pypSource: 'CGSSB Mandi Inspector 2021',
    pypAppearances: [
      { examName: 'CGSSB Mandi Inspector', year: 2021 },
      { examName: 'CGPSC State Service Prelims', year: 2018 },
      { examName: 'CG Vyapam Cultural Officer', year: 2016 },
    ],
    createdAt: '2024-01-20',
  },

  // Questions for CGPSC SSE (2 Marks each, -1/3rd marks negative)
  // 11
  {
    id: 'q-psc-01',
    subject: 'Chhattisgarh Special Knowledge',
    topic: 'History of Chhattisgarh',
    subtopic: 'Modern State Formation (2000)',
    difficulty: 'Medium',
    category: 'CGPSC',
    questionText: 'On which date was Chhattisgarh officially carved out of Madhya Pradesh as the 26th State of the Republic of India?',
    questionHindi: 'छत्तीसगढ़ आधिकारिक तौर पर मध्य प्रदेश से अलग होकर भारत गणराज्य का 26वां राज्य किस तिथि को बना?',
    options: [
      { id: 'A', text: '1st November 2000', textHindi: '1 नवंबर 2000' },
      { id: 'B', text: '9th November 2000', textHindi: '9 नवंबर 2000' },
      { id: 'C', text: '15th November 2000', textHindi: '15 नवंबर 2000' },
      { id: 'D', text: '26th January 2001', textHindi: '26 जनवरी 2001' },
    ],
    correctOption: 'A',
    marks: 2.0,
    negativeMarks: 0.667,
    explanation: 'Under the Madhya Pradesh Reorganisation Act 2000, Chhattisgarh was established on 1st November 2000 with Raipur as its capital.',
    explanationHindi: 'मध्य प्रदेश पुनर्गठन अधिनियम 2000 के तहत 1 नवंबर 2000 को छत्तीसगढ़ 26वें राज्य के रूप में अस्तित्व में आया।',
    pypSource: 'CGPSC SSE Prelims 2022',
    pypAppearances: [
      { examName: 'CGPSC SSE Prelims Paper-I', year: 2022, shift: 'General Studies' },
      { examName: 'CGSSB Combined Exam', year: 2016 },
      { examName: 'CG Vyapam Patwari', year: 2014 },
    ],
    createdAt: '2024-01-21',
  },
  // 12
  {
    id: 'q-psc-02',
    subject: 'Chhattisgarh Special Knowledge',
    topic: 'Geography & Natural Resources',
    subtopic: 'Minerals & Industrial Zones',
    difficulty: 'Medium',
    category: 'CGPSC',
    questionText: 'Which district of Chhattisgarh is globally renowned for Bailadila iron ore mines, supplying high-grade hematite?',
    questionHindi: 'बैलाडीला लौह अयस्क खदानों के लिए छत्तीसगढ़ का कौन सा जिला प्रसिद्ध है, जहां से उच्च कोटि का हेमेटाइट प्राप्त होता है?',
    options: [
      { id: 'A', text: 'Dantewada', textHindi: 'दंतेवाड़ा' },
      { id: 'B', text: 'Korba', textHindi: 'कोरबा' },
      { id: 'C', text: 'Raigarh', textHindi: 'रायगढ़' },
      { id: 'D', text: 'Surguja', textHindi: 'सरगुजा' },
    ],
    correctOption: 'A',
    marks: 2.0,
    negativeMarks: 0.667,
    explanation: 'Bailadila range in Dantewada district is famous for its massive deposits of top-grade hematite iron ore, exported via Visakhapatnam port by NMDC.',
    explanationHindi: 'दंतेवाड़ा जिले की बैलाडीला पहाड़ियों में विश्वस्तरीय हेमेटाइट लौह अयस्क पाया जाता है, जिसका खनन NMDC द्वारा किया जाता है।',
    pypSource: 'CGPSC SSE Prelims 2023',
    pypAppearances: [
      { examName: 'CGPSC SSE Prelims Paper-I', year: 2023, shift: 'General Studies' },
      { examName: 'CGSSB Mining Inspector', year: 2021 },
      { examName: 'CG Vyapam Labour Inspector', year: 2018 },
    ],
    createdAt: '2024-01-22',
  },
  // 13
  {
    id: 'q-psc-03',
    subject: 'Chhattisgarh Special Knowledge',
    topic: 'Culture, Tribes & Tourism',
    subtopic: 'Tribal Traditions (Gond, Baiga, Maria)',
    difficulty: 'Hard',
    category: 'CGPSC',
    questionText: 'The traditional "Ghotul" youth dormitory institution is primarily practiced by which tribe of Chhattisgarh?',
    questionHindi: 'पारंपरिक युवा गृह संस्था "घोटुल" मुख्य रूप से छत्तीसगढ़ की किस जनजाति द्वारा संचालित की जाती है?',
    options: [
      { id: 'A', text: 'Muria (Gond sub-tribe)', textHindi: 'मुरिया (गोंड उप-जनजाति)' },
      { id: 'B', text: 'Kamar', textHindi: 'कमर' },
      { id: 'C', text: 'Birhor', textHindi: 'बिरहोर' },
      { id: 'D', text: 'Halba', textHindi: 'हलबा' },
    ],
    correctOption: 'A',
    marks: 2.0,
    negativeMarks: 0.667,
    explanation: 'The Ghotul is an ancient cultural dormitory system of the Muria tribe of Bastar, documented extensively by anthropologist Verrier Elwin.',
    explanationHindi: 'घोटुल बस्तर के मुरिया आदिवासियों का पारंपरिक सामाजिक व सांस्कृतिक युवागृह है, जिसका अध्ययन वेरियर एल्विन ने अपनी पुस्तक में किया।',
    pypSource: 'CGPSC SSE Prelims 2021',
    pypAppearances: [
      { examName: 'CGPSC SSE Prelims Paper-I', year: 2021 },
      { examName: 'CGPSC State Service Mains', year: 2017 },
      { examName: 'CGSSB Mandi Inspector', year: 2016 },
    ],
    createdAt: '2024-01-23',
  },
  // 14
  {
    id: 'q-psc-04',
    subject: 'Chhattisgarh Special Knowledge',
    topic: 'History of Chhattisgarh',
    subtopic: 'Tribal Revolts & Freedom Struggle',
    difficulty: 'Hard',
    category: 'CGPSC',
    questionText: 'Who is recognized as the "First Martyr (Pratham Shaheed) of Chhattisgarh" during the 1857 Indian Freedom Struggle?',
    questionHindi: '1857 के स्वतंत्रता संग्राम में किसे "छत्तीसगढ़ का प्रथम शहीद" माना जाता है?',
    options: [
      { id: 'A', text: 'Veer Narayan Singh (Sonakhan)', textHindi: 'वीर नारायण सिंह (सोनाखान)' },
      { id: 'B', text: 'Hanuman Singh (Raipur Sepoy Mutiny)', textHindi: 'हनुमान सिंह' },
      { id: 'C', text: 'Surendra Sai', textHindi: 'सुरेंद्र साय' },
      { id: 'D', text: 'Kalyan Sahai', textHindi: 'कल्याण सहाय' },
    ],
    correctOption: 'A',
    marks: 2.0,
    negativeMarks: 0.667,
    explanation: 'Veer Narayan Singh, the landlord of Sonakhan, distributed grain to starving peasants and fought the British. He was executed in Raipur on 10 December 1857.',
    explanationHindi: 'सोनाखान के जमींदार वीर नारायण सिंह को अकाल पीड़ितों की सहायता व अंग्रेजी हुकूमत से बगावत के कारण 10 दिसंबर 1857 को रायपुर के जयस्तंभ चौक पर फांसी दी गई थी।',
    pypSource: 'CGPSC SSE Prelims 2023',
    pypAppearances: [
      { examName: 'CGPSC SSE Prelims Paper-I', year: 2023 },
      { examName: 'CGSSB Patwari', year: 2022 },
      { examName: 'CG Police Sub-Inspector (SI)', year: 2018 },
      { examName: 'CG Vyapam Revenue Inspector', year: 2015 },
    ],
    createdAt: '2024-01-24',
  },
  // 15
  {
    id: 'q-psc-05',
    subject: 'Chhattisgarh Special Knowledge',
    topic: 'Administration & Economy',
    subtopic: 'State Budget & Welfare Schemes',
    difficulty: 'Medium',
    category: 'CGPSC',
    questionText: 'Under the "Rajiv Gandhi Kisan Nyay Yojana" and subsequently upgraded farmer schemes in Chhattisgarh, what major cash incentive is provided for paddy procurement?',
    questionHindi: 'छत्तीसगढ़ में कृषक कल्याण योजनाओं के तहत धान खरीदी पर किसानों को कौन सा प्रमुख प्रोत्साहन प्रदान किया जाता है?',
    options: [
      { id: 'A', text: 'Input subsidy and guaranteed support price per quintal', textHindi: 'प्रति क्विंटल इनपुट सब्सिडी एवं सुनिश्चित समर्थन मूल्य (3100 रु/क्विंटल)' },
      { id: 'B', text: 'Free tractor distribution every 3 years', textHindi: 'प्रत्येक 3 वर्ष में निशुल्क ट्रैक्टर वितरण' },
      { id: 'C', text: '100% tax rebate on luxury goods', textHindi: 'विलासिता कर में 100% छूट' },
      { id: 'D', text: 'Free solar pumps to all non-farmers', textHindi: 'गैर-किसानों को सोलर पंप' },
    ],
    correctOption: 'A',
    marks: 2.0,
    negativeMarks: 0.667,
    explanation: 'Chhattisgarh provides historic minimum guaranteed support and input subsidy (Krishak Unnati / Nyay Yojana) ensuring farmers receive premium prices per quintal of paddy.',
    explanationHindi: 'छत्तीसगढ़ में धान उत्पादक किसानों को देश में सर्वाधिक समर्थन मूल्य व इनपुट सहायता प्रदान की जाती है।',
    pypSource: 'CGPSC SSE Prelims 2022',
    pypAppearances: [
      { examName: 'CGPSC SSE Prelims Paper-I', year: 2022 },
      { examName: 'CGSSB Rural Agriculture Extension Officer', year: 2021 },
    ],
    createdAt: '2024-01-25',
  },
  // 16
  {
    id: 'q-psc-06',
    subject: 'General Mental Ability & Reasoning',
    topic: 'Quantitative Aptitude',
    subtopic: 'Percentages & Profit-Loss',
    difficulty: 'Medium',
    category: 'CGPSC',
    questionText: 'A merchant purchases rice at ₹2500 per quintal and sells it at ₹3100 per quintal. What is his percentage profit?',
    questionHindi: 'एक व्यापारी ₹2500 प्रति क्विंटल की दर से धान खरीदकर ₹3100 प्रति क्विंटल पर बेचता है। उसका लाभ प्रतिशत क्या है?',
    options: [
      { id: 'A', text: '20%', textHindi: '20%' },
      { id: 'B', text: '24%', textHindi: '24%' },
      { id: 'C', text: '25%', textHindi: '25%' },
      { id: 'D', text: '30%', textHindi: '30%' },
    ],
    correctOption: 'B',
    marks: 2.0,
    negativeMarks: 0.667,
    explanation: 'Profit = ₹3100 - ₹2500 = ₹600. Percentage Profit = (600 / 2500) * 100 = 24%.',
    explanationHindi: 'लाभ = 3100 - 2500 = 600 रुपये। लाभ % = (600 / 2500) × 100 = 24%.',
    pypSource: 'CGPSC CSAT 2022',
    pypAppearances: [
      { examName: 'CGPSC SSE Paper-II (CSAT)', year: 2022 },
      { examName: 'CGSSB Combined Exam', year: 2020 },
    ],
    createdAt: '2024-01-26',
  },
  // 17
  {
    id: 'q-psc-07',
    subject: 'Chhattisgarh Special Knowledge',
    topic: 'Geography & Natural Resources',
    subtopic: 'Forests & National Parks',
    difficulty: 'Medium',
    category: 'CGPSC',
    questionText: 'Which is the only National Park in Chhattisgarh that is home to the endangered Bastar Hill Myna, the State Bird of Chhattisgarh?',
    questionHindi: 'छत्तीसगढ़ का कौन सा राष्ट्रीय उद्यान राज्य पक्षी "पहाड़ी मैना" का प्राकृतिक संरक्षण केंद्र है?',
    options: [
      { id: 'A', text: 'Kanger Valley National Park', textHindi: 'कांगेर घाटी राष्ट्रीय उद्यान' },
      { id: 'B', text: 'Guru Ghasidas National Park', textHindi: 'गुरु घासीदास राष्ट्रीय उद्यान' },
      { id: 'C', text: 'Indravati National Park', textHindi: 'इंद्रावती राष्ट्रीय उद्यान' },
      { id: 'D', text: 'Barnawapara Wildlife Sanctuary', textHindi: 'बारनवापारा वन्यजीव अभयारण्य' },
    ],
    correctOption: 'A',
    marks: 2.0,
    negativeMarks: 0.667,
    explanation: 'Kanger Valley National Park in Bastar district is the prime habitat and conservation sanctuary for the Bastar Hill Myna (Gracula religiosa peninsularis).',
    explanationHindi: 'कांगेर घाटी राष्ट्रीय उद्यान (बस्तर) में छत्तीसगढ़ का राजकीय पक्षी पहाड़ी मैना सुरक्षित वातावरण में पाया जाता है।',
    pypSource: 'CGPSC SSE Prelims 2021',
    pypAppearances: [
      { examName: 'CGPSC SSE Prelims Paper-I', year: 2021 },
      { examName: 'CG Vyapam Forest Guard', year: 2019 },
      { examName: 'CGSSB Assistant Conservator of Forest', year: 2017 },
    ],
    createdAt: '2024-01-27',
  },
  // 18
  {
    id: 'q-psc-08',
    subject: 'General Hindi & Chhattisgarhi Language',
    topic: 'Samanya Hindi',
    subtopic: 'Sandhi & Samas',
    difficulty: 'Medium',
    category: 'CGPSC',
    questionText: 'What is the correct Sandhi-Vichhed of the word "यद्यपि" (Yadyapi)?',
    questionHindi: '"यद्यपि" शब्द का सही संधि-विच्छेद क्या होगा?',
    options: [
      { id: 'A', text: 'यदि + अपि (Yan Sandhi)', textHindi: 'यदि + अपि (यण संधि)' },
      { id: 'B', text: 'यद + यपि', textHindi: 'यद + यपि' },
      { id: 'C', text: 'यद्या + अपि', textHindi: 'यद्या + अपि' },
      { id: 'D', text: 'यद्य + अपि', textHindi: 'यद्य + अपि' },
    ],
    correctOption: 'A',
    marks: 2.0,
    negativeMarks: 0.667,
    explanation: 'इ/ई + भिन्न स्वर = य् (यण संधि). Hence यदि + अपि = यद्यपि.',
    explanationHindi: 'यण स्वर संधि के नियमानुसार यदि + अपि = यद्यपि (इ + अ = य).',
    pypSource: 'CGPSC SSE Mains/Prelims 2022',
    pypAppearances: [
      { examName: 'CGPSC SSE Prelims Paper-II', year: 2022 },
      { examName: 'CGSSB Teacher Recruitment', year: 2019 },
    ],
    createdAt: '2024-01-28',
  },
  // 19
  {
    id: 'q-psc-09',
    subject: 'Child Pedagogy & Teaching Methodology',
    topic: 'Pedagogy & Curriculum',
    subtopic: 'National Education Policy 2020',
    difficulty: 'Easy',
    category: 'SWAMI_ATMANAND',
    questionText: 'Under the National Education Policy (NEP) 2020, what is the new pedagogical curricular structure replacing the 10+2 system?',
    questionHindi: 'राष्ट्रीय शिक्षा नीति (NEP) 2020 के अनुसार 10+2 प्रणाली के स्थान पर नया शैक्षणिक ढांचा क्या है?',
    options: [
      { id: 'A', text: '5 + 3 + 3 + 4', textHindi: '5 + 3 + 3 + 4' },
      { id: 'B', text: '5 + 4 + 3 + 2', textHindi: '5 + 4 + 3 + 2' },
      { id: 'C', text: '4 + 3 + 3 + 5', textHindi: '4 + 3 + 3 + 5' },
      { id: 'D', text: '3 + 3 + 4 + 5', textHindi: '3 + 3 + 4 + 5' },
    ],
    correctOption: 'A',
    marks: 1.0,
    negativeMarks: 0.333,
    explanation: 'NEP 2020 introduces the 5+3+3+4 structure corresponding to Foundational (5 yrs), Preparatory (3 yrs), Middle (3 yrs), and Secondary (4 yrs) stages.',
    explanationHindi: 'NEP 2020 में 5+3+3+4 प्रणाली लागू की गई है (बुनियादी 5 वर्ष, प्रारंभिक 3 वर्ष, माध्यमिक 3 वर्ष, उच्चतर माध्यमिक 4 वर्ष)।',
    pypSource: 'Swami Atmanand Teacher Recruitment 2022',
    pypAppearances: [
      { examName: 'Swami Atmanand Teacher Recruitment', year: 2022 },
      { examName: 'CG TET (Teacher Eligibility Test) Paper-II', year: 2023 },
    ],
    createdAt: '2024-01-29',
  },
  // 20
  {
    id: 'q-psc-10',
    subject: 'Child Pedagogy & Teaching Methodology',
    topic: 'Educational Psychology',
    subtopic: 'Learning Theories (Piaget, Vygotsky)',
    difficulty: 'Medium',
    category: 'SWAMI_ATMANAND',
    questionText: 'The concept of "Zone of Proximal Development" (ZPD) was formulated by which renowned educational psychologist?',
    questionHindi: '"समीपस्थ विकास का क्षेत्र" (ZPD - Zone of Proximal Development) का सिद्धांत किस मनोवैज्ञानिक द्वारा प्रतिपादित किया गया था?',
    options: [
      { id: 'A', text: 'Lev Vygotsky', textHindi: 'लेव वायगोत्स्की' },
      { id: 'B', text: 'Jean Piaget', textHindi: 'जीन पियाजे' },
      { id: 'C', text: 'B.F. Skinner', textHindi: 'बी.एफ. स्किनर' },
      { id: 'D', text: 'Jerome Bruner', textHindi: 'जेरोम ब्रूनर' },
    ],
    correctOption: 'A',
    marks: 1.0,
    negativeMarks: 0.333,
    explanation: 'Lev Vygotsky developed ZPD, defining the difference between what a learner can do without help and what they can achieve with guidance (scaffolding).',
    explanationHindi: 'लेव वायगोत्स्की ने ZPD और सामाजिक अंतःक्रिया सिद्धांत दिया, जिसके अनुसार बच्चा मार्गदर्शक (MKO) की सहायता से सीखता है।',
    pypSource: 'Swami Atmanand Lecturer Exam 2023',
    pypAppearances: [
      { examName: 'Swami Atmanand English Medium Teacher Recruitment', year: 2023 },
      { examName: 'CG TET Primary & Upper Primary', year: 2022 },
      { examName: 'Central CTET Paper-II', year: 2021 },
    ],
    createdAt: '2024-01-30',
  },
];

export const INITIAL_MOCK_TESTS: MockTest[] = [
  {
    id: 'test-cgssb-01',
    title: 'CGSSB Vyapam Combined Exam Full Mock Test 01',
    category: 'CGSSB',
    description: 'Comprehensive 10-question demonstration of full CGSSB Vyapam 100-Question examination standard. Features CG Special GK, History, Reasoning, Computer Knowledge, and Language.',
    durationMinutes: 15, // Demo length set to 15 mins (regular 120 mins) so students can comfortably test countdown and auto-submit
    totalMarks: 10,
    marksPerQuestion: 1.0,
    negativeMarksPerQuestion: 0.333,
    sections: [
      {
        id: 'sec-cg-gk',
        name: 'Part A: CG Special Knowledge & History',
        questionIds: ['q-cg-01', 'q-cg-02', 'q-cg-03', 'q-cg-07', 'q-cg-08', 'q-cg-10'],
      },
      {
        id: 'sec-apt-lang',
        name: 'Part B: Reasoning, Computer & Language',
        questionIds: ['q-cg-04', 'q-cg-05', 'q-cg-06', 'q-cg-09'],
      },
    ],
    questionCount: 10,
    attemptsCount: 3420,
    passingPercentage: 45,
    isPublished: true,
    createdAt: '2024-02-01',
  },
  {
    id: 'test-cgpsc-01',
    title: 'CGPSC State Service Preliminary Exam Paper-I Mock 01',
    category: 'CGPSC',
    description: 'Aligned strictly with CGPSC State Service Exam (SSE) Prelims General Studies syllabus. Total 10 demo questions, 2 marks per question, and 1/3rd negative marking (-0.667 marks).',
    durationMinutes: 15,
    totalMarks: 20,
    marksPerQuestion: 2.0,
    negativeMarksPerQuestion: 0.667,
    sections: [
      {
        id: 'sec-cgpsc-gs',
        name: 'Section 1: General Studies & CG History',
        questionIds: ['q-psc-01', 'q-psc-02', 'q-psc-03', 'q-psc-04', 'q-psc-05'],
      },
      {
        id: 'sec-cgpsc-csat',
        name: 'Section 2: Geography, Environment & Aptitude',
        questionIds: ['q-psc-06', 'q-psc-07', 'q-psc-08', 'q-cg-02', 'q-cg-06'],
      },
    ],
    questionCount: 10,
    attemptsCount: 4890,
    passingPercentage: 50,
    isPublished: true,
    createdAt: '2024-02-05',
  },
  {
    id: 'test-atmanand-01',
    title: 'Swami Atmanand English Medium Teachers & Lecturers Mock Paper 01',
    category: 'SWAMI_ATMANAND',
    description: 'Designed specifically for Swami Atmanand English Medium School recruitment candidates. Tests Child Pedagogy, Educational Psychology, NEP 2020, and State Knowledge.',
    durationMinutes: 15,
    totalMarks: 10,
    marksPerQuestion: 1.0,
    negativeMarksPerQuestion: 0.333,
    sections: [
      {
        id: 'sec-pedagogy',
        name: 'Section 1: Pedagogy & Education NEP 2020',
        questionIds: ['q-psc-09', 'q-psc-10', 'q-cg-04', 'q-cg-09', 'q-cg-06'],
      },
      {
        id: 'sec-cg-culture',
        name: 'Section 2: CG Special & Language Skills',
        questionIds: ['q-cg-01', 'q-cg-02', 'q-cg-03', 'q-cg-05', 'q-cg-10'],
      },
    ],
    questionCount: 10,
    attemptsCount: 2150,
    passingPercentage: 50,
    isPublished: true,
    createdAt: '2024-02-10',
  },
];

export const INITIAL_PYP_PAPERS: PreviousYearPaper[] = [
  {
    id: 'pyp-cgssb-patwari-2023',
    title: 'CGSSB Patwari Official Question Paper 2023',
    examCategory: 'CGSSB',
    year: 2023,
    totalQuestions: 150,
    durationMinutes: 180,
    marks: 150,
    negativeMarkingRatio: '-⅓rd (0.33 Marks)',
    testId: 'test-cgssb-01',
    paperSummary: 'Actual question paper conducted by Chhattisgarh Vyapam for Patwari recruitment. Covers Computer (20 Qs), Hindi (10 Qs), English (10 Qs), Math/Reasoning (30 Qs), and CG General Knowledge (35 Qs).',
    subjectsWeightage: [
      { subject: 'CG Special Knowledge', questionCount: 35, percentage: 23.3 },
      { subject: 'Quantitative & Reasoning', questionCount: 30, percentage: 20.0 },
      { subject: 'Computer Knowledge', questionCount: 20, percentage: 13.3 },
      { subject: 'General Hindi & English', questionCount: 20, percentage: 13.3 },
      { subject: 'Current Affairs & National GK', questionCount: 45, percentage: 30.1 },
    ],
    downloadFileName: 'CGSSB_Patwari_2023_Official_Solved.pdf',
    fileSize: '3.4 MB',
  },
  {
    id: 'pyp-cgpsc-sse-2023',
    title: 'CGPSC State Service Prelims Paper-I (General Studies) 2023',
    examCategory: 'CGPSC',
    year: 2023,
    totalQuestions: 100,
    durationMinutes: 120,
    marks: 200,
    negativeMarkingRatio: '-⅓rd (0.667 Marks per wrong answer)',
    testId: 'test-cgpsc-01',
    paperSummary: 'Official CGPSC Prelims Paper-I containing 50 questions on Indian History, Geography & Constitution and 50 in-depth questions on Chhattisgarh Tribes, Art, History, and Economy.',
    subjectsWeightage: [
      { subject: 'Chhattisgarh History & Culture', questionCount: 25, percentage: 25.0 },
      { subject: 'Chhattisgarh Geography & Economy', questionCount: 25, percentage: 25.0 },
      { subject: 'Indian Polity & Constitution', questionCount: 18, percentage: 18.0 },
      { subject: 'General Science & Tech', questionCount: 16, percentage: 16.0 },
      { subject: 'Current Events & Schemes', questionCount: 16, percentage: 16.0 },
    ],
    downloadFileName: 'CGPSC_SSE_Prelims_2023_Paper1.pdf',
    fileSize: '4.8 MB',
  },
  {
    id: 'pyp-atmanand-lecturer-2022',
    title: 'Swami Atmanand Lecturer & Teacher Recruitment Exam 2022',
    examCategory: 'SWAMI_ATMANAND',
    year: 2022,
    totalQuestions: 100,
    durationMinutes: 120,
    marks: 100,
    negativeMarkingRatio: '-⅓rd (0.33 Marks)',
    testId: 'test-atmanand-01',
    paperSummary: 'Actual recruitment paper for English Medium school teachers and lecturers under Swami Atmanand Excellence School Scheme. Emphasis on pedagogy, teaching methods, and English comprehension.',
    subjectsWeightage: [
      { subject: 'Child Pedagogy & Teaching Aptitude', questionCount: 30, percentage: 30.0 },
      { subject: 'English Language & Comprehension', questionCount: 25, percentage: 25.0 },
      { subject: 'CG Knowledge & Culture', questionCount: 25, percentage: 25.0 },
      { subject: 'Reasoning & Mental Ability', questionCount: 20, percentage: 20.0 },
    ],
    downloadFileName: 'Swami_Atmanand_Lecturer_2022_Solved.pdf',
    fileSize: '2.9 MB',
  },
  {
    id: 'pyp-cgssb-ri-2021',
    title: 'CGSSB Revenue Inspector (RI) Exam 2021',
    examCategory: 'CGSSB',
    year: 2021,
    totalQuestions: 150,
    durationMinutes: 180,
    marks: 150,
    negativeMarkingRatio: '-⅓rd (0.33 Marks)',
    testId: 'test-cgssb-01',
    paperSummary: 'Official Revenue Inspector question paper from Vyapam. Strong focus on revenue laws, land measurements, CG geography, and mental aptitude.',
    subjectsWeightage: [
      { subject: 'Chhattisgarh Special & Land Laws', questionCount: 50, percentage: 33.3 },
      { subject: 'Maths & Mental Ability', questionCount: 40, percentage: 26.7 },
      { subject: 'Computer Applications', questionCount: 20, percentage: 13.3 },
      { subject: 'General Knowledge & Language', questionCount: 40, percentage: 26.7 },
    ],
    downloadFileName: 'CGSSB_Revenue_Inspector_2021.pdf',
    fileSize: '3.1 MB',
  },
];

export const SAMPLE_USER_ATTEMPTS: TestAttempt[] = [
  {
    id: 'att-sample-01',
    userId: 'u-student-01',
    userName: 'Rameshwar Dewangan',
    testId: 'test-cgssb-01',
    testTitle: 'CGSSB Vyapam Combined Exam Full Mock Test 01',
    category: 'CGSSB',
    submittedAt: '2024-03-14T10:45:00.000Z',
    timeTakenSeconds: 580,
    totalDurationSeconds: 900,
    responses: {
      'q-cg-01': 'A',
      'q-cg-02': 'B',
      'q-cg-03': 'C',
      'q-cg-04': 'C',
      'q-cg-05': 'B',
      'q-cg-06': 'A',
      'q-cg-07': 'A',
      'q-cg-08': 'A',
      'q-cg-09': 'B',
      'q-cg-10': 'A',
    },
    questionStatuses: {
      'q-cg-01': 'answered',
      'q-cg-02': 'answered',
      'q-cg-03': 'answered',
      'q-cg-04': 'answered',
      'q-cg-05': 'answered',
      'q-cg-06': 'answered',
      'q-cg-07': 'answered',
      'q-cg-08': 'answered',
      'q-cg-09': 'answered',
      'q-cg-10': 'answered',
    },
    score: 10.0,
    maxScore: 10.0,
    percentage: 100,
    accuracy: 100,
    correctCount: 10,
    incorrectCount: 0,
    unattemptedCount: 0,
    markedForReviewCount: 1,
    negativeMarksDeducted: 0,
    simulatedRank: 42,
    totalParticipants: 3420,
    percentile: 98.8,
    sectorAnalysis: [
      {
        subject: 'Chhattisgarh Special Knowledge',
        total: 6,
        correct: 6,
        incorrect: 0,
        unattempted: 0,
        accuracy: 100,
        score: 6.0,
        maxScore: 6.0,
        timeSpentSeconds: 320,
      },
      {
        subject: 'General Science & Computer Knowledge',
        total: 2,
        correct: 2,
        incorrect: 0,
        unattempted: 0,
        accuracy: 100,
        score: 2.0,
        maxScore: 2.0,
        timeSpentSeconds: 110,
      },
      {
        subject: 'General Mental Ability & Reasoning',
        total: 1,
        correct: 1,
        incorrect: 0,
        unattempted: 0,
        accuracy: 100,
        score: 1.0,
        maxScore: 1.0,
        timeSpentSeconds: 85,
      },
      {
        subject: 'General Hindi & Chhattisgarhi Language',
        total: 1,
        correct: 1,
        incorrect: 0,
        unattempted: 0,
        accuracy: 100,
        score: 1.0,
        maxScore: 1.0,
        timeSpentSeconds: 65,
      },
    ],
  },
];

export const INITIAL_ATTEMPTS = SAMPLE_USER_ATTEMPTS;
